### ISSUE TITLE
Warning: Calling depends_on :macos => :mavericks is deprecated!

### ISSUE THREAD

**Issue by CodeByZach** [Shopify/homebrew-shopify#183] opened 2020-09-02 14:16 UTC
<img width="636" alt="image" src="https://user-images.githubusercontent.com/20159826/91995086-61398380-ed05-11ea-8b79-90a43ec62f85.png">

**Comment by andyw8** [comment] 2021-02-05 15:51
Duplicate of #168

**Closed by andyw8** 2021-02-05 15:51 UTC
