### ISSUE TITLE
warning on brew update

### ISSUE THREAD

**Issue by ryb73** [Shopify/homebrew-shopify#165] opened 2020-06-20 23:06 UTC
Saw the following after running `brew update`:
```
Warning: Calling depends_on :macos => :mavericks is deprecated! There is no replacement.
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/qt@5.5.rb:28
```

**Comment by EatBreatheCode** [comment] 2020-09-02 14:16
Same here

**Comment by andyw8** [comment] 2021-02-05 15:52
Duplicate of #168

**Closed by andyw8** 2021-02-05 15:52 UTC
